### ISSUE TITLE
Switch from jgitflow-maven-plugin to gitflow-maven-plugin

### ISSUE THREAD

**Issue by s-spindler** [deviceinsight/helm-maven-plugin#11]
We are still using the jgitflow-maven-plugin which is not maintained anymore.
We have already switched to the [gitflow-maven-plugin](https://github.com/aleksandr-m/gitflow-maven-plugin) in several of our projects and should do the same here.

**Comment by j-oliver** [comment]
I'd like to take this!

**Comment by pvorb** [comment]
@j-oliver Please go ahead :+1:
