### ISSUE TITLE
Add support for configuring the full upload URL

### ISSUE THREAD

**Issue by Hervian** [deviceinsight/helm-maven-plugin#20]
Add support for configuring the full upload URL.

Currently the upload URL is only **partly** configurable, namely via the `chartRepoUrl `parameter. 
But the upload URL is the value of that parameter with the suffix `/api/charts`.  

Source:  `https://github.com/deviceinsight/helm-maven-plugin/blob/develop/src/main/kotlin/com/deviceinsight/helm/DeployMojo.kt`

It would be nice if the full URL was configurable. Otherwise I must construct the post call via another plugin.

**Comment by pvorb** [comment]
So you are using some other chart registry than ChartMuseum? What are you using instead?

Would you be interested in providing the feature on your own in a Pull Request?

**Comment by trnl** [comment]
@pvorb, @Hervian, grateful if you can check
