### ISSUE TITLE
Add support for Helm 3

### ISSUE THREAD

**Issue by pvorb** [deviceinsight/helm-maven-plugin#21]
Helm 3 was released in November 2019. We should make sure the plugin works with both Helm 2 and 3.

**Comment by foal** [comment]
Error creating helm chart: Could not download file from https://kubernetes-helm.storage.googleapis.com/helm-v3.1.0-windows-amd64.zip -> [Help 1]

**Comment by cr-kobyisrael** [comment]
@foal  try https://get.helm.sh/helm-v3.1.0-windows-amd64.tar.gz

**Comment by foal** [comment]
Thank you. I already have 3.1.1 :) 
Problem is that I don't know how to force the plugin to download helm version 3 or use local binaries

**Comment by pvorb** [comment]
@foal You should be able to add

~~~ xml
<helmDownloadUrl>https://get.helm.sh/</helmDownloadUrl>
~~~

to the plugin configuration and it should download https://get.helm.sh/helm-v3.1.1-windows-amd64.zip rather than https://kubernetes-helm.storage.googleapis.com/helm-v3.1.1-windows-amd64.zip.

Let me know if that helps.

**Comment by foal** [comment]
Thank you! It helped with download, but not with helm3 - next error is 
```
[INFO] Clear target directory to ensure clean target package
[INFO] Created target helm directory
[ERROR] Output: Error: unknown flag: --client-only
```

**Comment by pvorb** [comment]
Thanks for the hint. Calling `helm init --client-only` is now only done if you are using Helm 2. @foal Can you please check out the latest `develop` branch of this repository, do a `./mvnw install` and retest the behavior with version `2.3.0-SNAPSHOT`?

**Comment by foal** [comment]
Ok, looks like it works, at least for my simple charts.

Thank you!

**Comment by pvorb** [comment]
Awesome :tada:
