### ISSUE TITLE
Support local helm binary support

### ISSUE THREAD

**Issue by cr-kobyisrael** [deviceinsight/helm-maven-plugin#22]
Mainly for CI, it would be nice to be able to use local helm binary and not download helm binary each time.

**Comment by pvorb** [comment]
The plugin actually reuses a previously downloaded helm binary. You probably just need to cache the directory `~/.m2/repository` between builds. (Or `~/.m2/repository/com/deviceinsight/helm/helm` if you want to be more specific.)

**Comment by cr-kobyisrael** [comment]
@pvorb Thanks for your quick reply.

Sometimes there isn't an option to download helm for security reasons, and in some use-cases developer doesn't know which helm version will run (as long as major version aligned) in the CI server, it's just there under some using environment variable path.

Any thoughts?

**Comment by pvorb** [comment]
In this case, a workaround would be to create a symlink to helm at the location in the local Maven repository.

~~~
#!/bin/sh
helm_version=2.13.0 # or whatever you configured as `<helmVersion>` in the plugin (should also match the version of the locally installed helm binary)
target=$(which helm)
dir="~/.m2/repository/com/deviceinsight/helm/helm/$helm_version"
mkdir -p "$dir"
ln -s "$target" -t "$dir"
mv "$dir/helm" "$dir/helm-$helm_version-linux-amd64.binary"
~~~

This way, the plugin thinks the file was downloaded already and doesn't attempt to load it again.

**Comment by cr-kobyisrael** [comment]
Thanks for you help!
