### ISSUE TITLE
[Version 2.3.0] deploy uses project.version instead of chartVersion 

### ISSUE THREAD

**Issue by kobynet** [deviceinsight/helm-maven-plugin#29]
In version 2.3.0 we added chartVersion param for overriding the chart version in this pr https://github.com/deviceinsight/helm-maven-plugin/pull/24, this works for lint,package,template commands, but does not work for deploy command since it does not inherit from [AbstractHelmMojo](https://github.com/deviceinsight/helm-maven-plugin/blob/develop/src/main/kotlin/com/deviceinsight/helm/AbstractHelmMojo.kt).

I'll create a pr for this.

**Comment by cr-kobyisrael** [comment]
@pvorb This can be closed

**Comment by pvorb** [comment]
Yep, you were faster than me. ;)
