### ISSUE TITLE
chartRepoUrl is required for package goal but can't easily be made optional

### ISSUE THREAD

**Issue by jmpavlec** [deviceinsight/helm-maven-plugin#39]
I created https://github.com/deviceinsight/helm-maven-plugin/pull/38 to show how it could be made optional. For our use case, we don't need to add a chart repo. It appears to already been optional for the [deploy phase](https://github.com/deviceinsight/helm-maven-plugin/blob/develop/src/main/kotlin/com/deviceinsight/helm/DeployMojo.kt#L59) (although one would argue about whether that should actually be allowed)

I see this has been somewhat covered before: https://github.com/deviceinsight/helm-maven-plugin/issues/5

I'm not sure why using a specific chart repo should be the solution.

**Comment by kobynet** [comment]
This totally makes for our use-case as well... in our ci/cd server, we have this pre-configured.

**Comment by pvorb** [comment]
Fixed by #38
