### ISSUE TITLE
Invalid cookie header: "Set-Cookie: AWSALB=...”

### ISSUE THREAD

**Issue by xueshanf** [deviceinsight/helm-maven-plugin#45]
helm-maven-plugin:2.4.1

When uploading helm chart to Chartmuseum behind AWS ALB, I am getting the flowing warnings:

```
WARNING: Invalid cookie header: "Set-Cookie: AWSALB=xxxxxxxxxxxxxxxxxxx; Expires=Tue, 18 Aug 2020 06:25:40 GMT; Path=/". Invalid 'expires' attribute: Tue, 18 Aug 2020 06:25:40 GMT
```
The helm chart is uploaded despite the warnings.

It would be nice to be able to disable the cookie header checks or fix the warnings. Thanks!

**Comment by pvorb** [comment]
I fixed this in helm-maven-plugin 2.5.1, which should shortly arrive on Maven Central.
