### ISSUE TITLE
Optional chartRepoUrl

### ISSUE THREAD

**Issue by kalexmills** [deviceinsight/helm-maven-plugin#5]
Why do I need to specify a `chartRepoUrl` in order to package and lint my chart? Could this be optional?

**Comment by kalexmills** [comment]
Disregard -- looks like this is used for grabbing chart dependencies, I thought it was for publishing.

Anyone else struggling with this can set `<chartRepoUrl>https://kubernetes-charts.storage.googleapis.com/</chartRepoUrl>`

**Comment by pvorb** [comment]
Thank you for mentioning this. I'll update the readme accordingly.

**Comment by pvorb** [comment]
I've updated the readme. This already was optional, defaulting to `https://kubernetes-charts.storage.googleapis.com/`, but the readme was outdated. So you don't have to define it.

**Comment by fforloff** [comment]
Removing chartRepoUrl I'm getting
`Failed to execute goal com.deviceinsight.helm:helm-maven-plugin:2.1.0:package (default) on project incoming-generator: The parameters 'chartRepoUrl' for goal com.deviceinsight.helm:helm-maven-plugin:2.1.0:package are missing or invalid`

Aslo as per the original post, can this parameter be truly optional (i.e. not defaulting to https://kubernetes-charts.storage.googleapis.com/)?
