### ISSUE TITLE
helm:lint does not create /target/helm directory

### ISSUE THREAD

**Issue by kalexmills** [deviceinsight/helm-maven-plugin#6]
Seems that the helm:lint does not create the /target/helm directory -- which means linting before packaging will fail with `No such file or directory`.

```
[ERROR] Failed to execute goal com.deviceinsight.helm:helm-maven-plugin:2.1.0:lint (default) on project relos-api: Error rendering helm lint: Cannot run program "/Users/username/.m2/repository/com/deviceinsight/helm/helm/2.13.1/helm-2.13.1-darwin-amd64.binary" (in directory "/Users/username/projectname/target/helm"): error=2, No such file or directory 
```

**Comment by pvorb** [comment]
Linting is assumed to be executed after packaging, but switching order is legit, so I'll fix this.

**Comment by pvorb** [comment]
:thinking: The `target/helm` directory is deleted [here](https://github.com/deviceinsight/helm-maven-plugin/blob/develop/src/main/kotlin/com/deviceinsight/helm/PackageMojo.kt#L60-L62) in the `package` goal, so this doesn't make much sense in most cases. I also think linting without executing the `package` goal will not work even if the `target/helm` directory exists.

Do you have a use case, where packaging before linting doesn't make sense?

**Comment by kalexmills** [comment]
My understanding of how `helm lint` works may be off. I thought the goal was linting the source, not the source after it's been packaged.

Would it be too much trouble to lint from the source, to provide more flexibility? For instance, I can run `helm lint` from `src/main/helm/<chart-name>` and it works.

Some may like to avoid even packaging a chart that fails to lint, but I guess the other option is not to deploy it. As long as we have a test in place to avoid pushing bad artifacts, that is okay.

**Comment by pvorb** [comment]
One feature of the `helm-maven-plugin` is to replace placeholders like `${project.version}` in Helm Charts and template files with the corresponding Maven properties. That needs to happen before running `helm lint` or `helm template` since these placeholders would otherwise cause syntax errors in many cases. That's the reasoning behind our requirement to run the `package` goal before the other goals.

**Comment by kalexmills** [comment]
Ah! That makes perfect sense. I am not using those features, so I hadn't realized. This is a good design choice, then.
