### ISSUE TITLE
package goal does not work with helm 3 (tested with 3.3.3)

### ISSUE THREAD

**Issue by random-dwi** [deviceinsight/helm-maven-plugin#61]
package goal fails with the following error:
```
[INFO] --- helm-maven-plugin:2.6.0:package (default) @ pon-api ---
[INFO] Clear target directory to ensure clean target package
[INFO] Created target helm directory
[ERROR] Output: Error: repository name (incubator) already exists, please specify a different name
[ERROR] Failed to execute goal com.deviceinsight.helm:helm-maven-plugin:2.6.0:package (default) on project pon-api: Error creating helm chart: When executing '/Users/x/.m2/repository/com/deviceinsight/helm/helm/3.3.3/helm-3.3.3-darwin-amd64.binary repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com' got result code '1' -> [Help 1]
```

This is caused by the following line:
https://github.com/deviceinsight/helm-maven-plugin/blob/develop/src/main/kotlin/com/deviceinsight/helm/PackageMojo.kt#L80

With helm2 `helm repo add`could be called multiple times. With helm3 the second invocation will throw an error.

**Comment by pvorb** [comment]
The behavior was changed with Helm 3 and to get the previous behavior, you have to add the option `--force-update` to `helm repo add`. So we could either add `--force-update` to the command when we detect that Helm 3 is used or we could remove the `helm repo add incubator` altogether. I think this would be cleaner, but it might break existing builds. In order to still be able to use incubator charts, we would have to add support for defining multiple repositories.

**Comment by random-dwi** [comment]
The `--force-update` flag has to be added regardless if the incubator repo is removed or not. The same will happen for the `repo add chartRepo` a few lines below in the code.
But I think removing the incubator repo and changing the chartRepo parameter into a list of parameters would be cleaner.
It is a breaking change but resolving it is quite easy.

**Comment by pvorb** [comment]
:+1: Yep, I agree. This would be a clean solution.

**Comment by pvorb** [comment]
This breaking change was [introduced in Helm v3.3.2](https://github.com/helm/helm/releases/tag/v3.3.2) and [reverted in v3.3.4](https://github.com/helm/helm/releases/tag/v3.3.4). In order to circumvent the issue, you can use a version >= v3.3.4.
