### ISSUE TITLE
Version of generated chart does not match version specified in Chart.yaml

### ISSUE THREAD

**Issue by OmriHarary** [deviceinsight/helm-maven-plugin#7]
When the plugin packages the chart it overrides the chart version from Chart.yaml with the project.model.version property. If the project version does not exactly conform to SemVer 2, (includes "-SNAPSHOT" for example) this causes several problems with Helm.

https://github.com/deviceinsight/helm-maven-plugin/blob/433757375c1f54705fe74d8626bbe867408f33ed/src/main/kotlin/com/deviceinsight/helm/PackageMojo.kt#L72

Beyond the SemVer strictness, the [Helm docs](https://helm.sh/docs/developing_charts/#charts-and-versioning) state that the version number in the chart name is assumed to match the one in Chart.yaml, and that "failure to meet this assumption will cause an error."

If anything, the project version should be used to set the [appVersion](https://helm.sh/docs/developing_charts/#the-appversion-field) Helm field, which versions the application included in the chart.

As it stands right now, a chart with a correctly set version in Chart.yaml but with a maven project version that does not meet Helm requirements will be packaged with the latter as its chart version and then will not be picked up by Helm CLI tooling.

**Comment by pvorb** [comment]
That's a valid point. We *always* keep Helm Chart versions 100% in sync with project versions, because that makes things easier for us. ("-SNAPSHOT" is treated as a pre-release identifier as expected, but it's not final, so not strictly compliant to SemVer.)

If you need separate versions for the chart and the project itself, we could add an option that doesn't specify versions via `--version` (and therefore ignores the version in the `Chart.yaml`. Would this solve your problem?

**Comment by OmriHarary** [comment]
That would be ideal, yeah.

**Comment by pvorb** [comment]
Oh, I’m sorry I missed your last comment. If you are still interested, here’s how I would do it:

1. Introduce a new property `inheritProjectVersion`, which defaults to `true` for compatibility reasons.
2. As far as I can tell, only [this line in the PackageMojo](https://github.com/deviceinsight/helm-maven-plugin/blob/develop/src/main/kotlin/com/deviceinsight/helm/PackageMojo.kt#L72) is affected. If `inheritProjectVersion` is `false`, the option `--version ${project.model.version}` should not be used.
3. Document the property [in the README](https://github.com/deviceinsight/helm-maven-plugin/blob/develop/README.adoc#configuration).

**Comment by fforloff** [comment]
+1 for this. Moving from the fabric8 helm plugin, which allowed any helm chart version, even non-SemVer 2 compliant, this seem to be quite a limitation.

**Comment by s-spindler** [comment]
Agreed, this would be a nice addition.
However, be aware that this does not have a high priority for us at the moment. As @pvorb pointed out, we are usually keeping chart version and project version in sync.
If anybody wants to pick this up, please refer to @pvorb's comment above regarding a possible way of implementing it.

**Comment by cr-kobyisrael** [comment]
+1

**Comment by kobynet** [comment]
> Oh, I’m sorry I missed your last comment. If you are still interested, here’s how I would do it:
> 
> 1. Introduce a new property `inheritProjectVersion`, which defaults to `true` for compatibility reasons.
> 2. As far as I can tell, only [this line in the PackageMojo](https://github.com/deviceinsight/helm-maven-plugin/blob/develop/src/main/kotlin/com/deviceinsight/helm/PackageMojo.kt#L72) is affected. If `inheritProjectVersion` is `false`, the option `--version ${project.model.version}` should not be used.
> 3. Document the property [in the README](https://github.com/deviceinsight/helm-maven-plugin/blob/develop/README.adoc#configuration).

After going through the code, there is another issue needs to be resolved when omitting the --version flag, it's in the following line
https://github.com/deviceinsight/helm-maven-plugin/blob/develop/src/main/kotlin/com/deviceinsight/helm/PackageMojo.kt#L85
which checks whether the right file was created in
https://github.com/deviceinsight/helm-maven-plugin/blob/develop/src/main/kotlin/com/deviceinsight/helm/AbstractHelmMojo.kt#L121

If we remove --version flag we need to figure out how we get the version for the file name.
Maybe extracting from Chart.yaml file or another method.

**Comment by pvorb** [comment]
There's now support for overriding the chart version. See #24 for more information.
