### ISSUE TITLE
Ubuntu arm 64 (aarch64) not supported

### ISSUE THREAD

**Issue by jon-entwistle** [deviceinsight/helm-maven-plugin#80]
Error message:

Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating helm chart: Unsupported platform architecture 'aarch64'

This affects all versions of the plugin.

Attaching patch to fix this issue.
[patch.zip](https://github.com/deviceinsight/helm-maven-plugin/files/5740047/patch.zip)

**Comment by pvorb** [comment]
Fixed by fbdbd9c

I've just released [version 2.8.1](https://github.com/deviceinsight/helm-maven-plugin/releases/tag/2.8.1). It will land in Maven Central's index soon.

**Comment by jon-entwistle** [comment]
Great - thanks!
