### ISSUE TITLE
Issue on init helm for packaging execution

### ISSUE THREAD

**Issue by 1140864** [deviceinsight/helm-maven-plugin#83]
Hi,

I'm having an issue when executing the mvn clean install and getting the following error.

[ERROR] Failed to execute goal com.deviceinsight.helm:helm-maven-plugin:2.8.1:package (default) on project test-k8s: Error creating helm chart: When executing '/root/.m2/repository/com/deviceinsight/helm/helm/2.14.3/helm-2.14.3-linux-amd64.binary init --client-only' got result code '1' -> [Help 1]

this is my pom build:

```
<build>
        <sourceDirectory>src/main/test</sourceDirectory>
        <outputDirectory>target/test</outputDirectory>
        <plugins>
            <plugin>
                <groupId>com.deviceinsight.helm</groupId>
                <artifactId>helm-maven-plugin</artifactId>
                <version>2.8.1</version>
                <configuration>
                    <chartFolder>src/main/test</chartFolder>
                    <chartRepoUrl>https://charts.helm.sh/stable</chartRepoUrl>
                    <helmVersion>2.14.3</helmVersion>
                    <strictLint>true</strictLint>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src\main\test</directory>
                <includes>
                    <include>**/*.yaml</include>
                    <include>**/*.properties</include>
                    <include>**/*.xml</include>
                </includes>
            </resource>
        </resources>
    </build>
```

Edit by @pvorb: Fix formatting of pom.xml

**Comment by pvorb** [comment]
Unfortunately I can't see what's wrong here.

I couldn't reproduce the problem with helm 2.14.3 linux-amd64. Could you maybe just run `mvn helm:package` and post the full output here? Typically, The interesting information comes directly after the line

    [INFO] --- helm-maven-plugin:2.8.1:package

It might have to do with your $HELM_HOME, but I can't tell for sure.

**Comment by pvorb** [comment]
I couldn't reproduce the problem because I still had everything in my local cache in `~/.helm`.

A colleague of mine hinted me that there really was a problem with this version of helm. You need to set at least `<helmVersion>2.17.0</helmVersion>` or `<helmVersion>3.4.2</helmVersion>`.
